"""
Weaviate Vector Database Client - ClaimBridge Integration

INTERVIEW EXPLANATION:
=====================
Why Weaviate?
- Stores document embeddings (vector representations) of policy documents
- Enables semantic search: "find similar policies" not just keyword match
- Multi-tenant safe: filters by company_id to prevent data leakage

How it works:
1. Documents (policies, guidelines) are converted to embeddings (768-dim vectors)
2. Stored in Weaviate with metadata (company_id, customer_id, doc_type)
3. When claim arrives, query Weaviate: "find policies similar to THIS claim"
4. Weaviate returns top-K most relevant documents using vector similarity
5. These documents go to LLM for analysis (RAG - Retrieval Augmented Generation)

Key patterns:
- METADATA FILTERING: Query only documents for specific company_id (multi-tenant isolation)
- HYBRID SEARCH: Combine keyword search + vector similarity for better results
- AUDIT LOGGING: Track what documents were retrieved for compliance
"""

import weaviate
from weaviate.classes.config import Configure, Property, DataType, VectorIndexType, Vectorizer
from weaviate.classes.query import MetadataQuery
import logging
from typing import List, Dict, Optional, Any
from datetime import datetime

logger = logging.getLogger(__name__)


class WeaviateClient:
    """
    Client for interacting with Weaviate vector database.

    Responsibilities:
    1. Connect to Weaviate instance
    2. Create/manage collections (schemas)
    3. Index documents with embeddings
    4. Retrieve relevant documents via semantic search
    5. Handle metadata filtering for multi-tenant isolation
    """

    def __init__(self, weaviate_url: str = "http://localhost:8080"):
        """
        Initialize Weaviate client.

        Args:
            weaviate_url: URL to Weaviate instance (default: localhost:8080)

        Interview point: Why connect to weaviate_url?
        - Weaviate runs in Docker container on port 8080
        - This connection is how we access the vector database
        - In production, this would be cloud-hosted (AWS/GCP/Azure)
        """
        try:
            self.client = weaviate.connect_to_local(
                host="localhost",
                port=8080,
                skip_init_checks=False
            )
            logger.info("✓ Connected to Weaviate")
        except Exception as e:
            logger.error(f"✗ Failed to connect to Weaviate: {str(e)}")
            raise

    def create_collections(self):
        """
        Create collections (schemas) in Weaviate for ClaimBridge.

        INTERVIEW EXPLANATION:
        A collection is like a table in SQL, but stores vectors.
        We need 3 collections:
        1. ClaimPolicies - Insurance policy documents
        2. ClaimGuidelines - Assessment guidelines
        3. ClaimHistory - Past similar claims for reference

        Why separate collections?
        - Different update frequencies (policies update quarterly, guidelines yearly)
        - Different retrieval strategies (policy search vs history search)
        - Better organization and monitoring
        """

        collections_to_create = [
            {
                "name": "ClaimPolicies",
                "description": "Insurance policy documents with embeddings"
            },
            {
                "name": "ClaimGuidelines",
                "description": "Claim assessment guidelines and rules"
            },
            {
                "name": "ClaimHistory",
                "description": "Historical claims for similarity matching"
            }
        ]

        for collection_info in collections_to_create:
            try:
                collection_name = collection_info["name"]

                # Check if collection already exists
                if self.client.collections.exists(collection_name):
                    logger.info(f"✓ Collection '{collection_name}' already exists")
                    continue

                # Create new collection
                # INTERVIEW POINT: Why these properties?
                # - content: The actual policy/guideline text
                # - embedding: Vector (auto-generated by text2vec-openai)
                # - company_id: CRITICAL for multi-tenant isolation
                # - customer_id: Filter by claimant
                # - doc_type: Distinguish policy vs guideline vs history
                # - metadata_: JSON for flexible extra data

                self.client.collections.create(
                    name=collection_name,
                    description=collection_info["description"],
                    properties=[
                        Property(
                            name="content",
                            data_type=DataType.TEXT,
                            description="Document text content"
                        ),
                        Property(
                            name="company_id",
                            data_type=DataType.TEXT,
                            description="Insurance company ID (multi-tenant filter)",
                            index=True  # Index for fast filtering
                        ),
                        Property(
                            name="customer_id",
                            data_type=DataType.TEXT,
                            description="Customer/claimant ID",
                            index=True
                        ),
                        Property(
                            name="doc_type",
                            data_type=DataType.TEXT,
                            description="Document type: policy | guideline | historical_claim",
                            index=True
                        ),
                        Property(
                            name="title",
                            data_type=DataType.TEXT,
                            description="Document title"
                        ),
                        Property(
                            name="source",
                            data_type=DataType.TEXT,
                            description="Where document came from (e.g., 'policy_2024_q1')"
                        ),
                        Property(
                            name="metadata_",
                            data_type=DataType.OBJECT,
                            description="Additional metadata as JSON"
                        ),
                        Property(
                            name="created_at",
                            data_type=DataType.DATE,
                            description="When document was indexed"
                        ),
                        Property(
                            name="updated_at",
                            data_type=DataType.DATE,
                            description="Last update timestamp"
                        )
                    ],
                    vectorizer_config=Configure.Vectorizer.text2vec_openai(
                        model="text-embedding-3-small"  # OpenAI embedding model
                    ),
                    vector_index_config=Configure.VectorIndex.hnsw(
                        distance_metric="cosine"  # Cosine distance for similarity
                    )
                )

                logger.info(f"✓ Created collection '{collection_name}'")

            except Exception as e:
                logger.error(f"✗ Error creating collection '{collection_name}': {str(e)}")

    def index_document(
        self,
        collection_name: str,
        content: str,
        company_id: str,
        customer_id: str,
        doc_type: str,
        title: str,
        source: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Index a document in Weaviate.

        INTERVIEW EXPLANATION:
        This takes a policy/guideline document and:
        1. Converts text to embedding (vector) automatically via text2vec-openai
        2. Stores vector + metadata in Weaviate
        3. Returns document UUID

        Why metadata fields matter:
        - company_id + customer_id: Multi-tenant isolation (don't leak Company A's docs to Company B)
        - doc_type: Filter by document category
        - source: Track where document originated (audit trail)
        - created_at: Know how fresh the data is

        Args:
            collection_name: Which collection to index into
            content: Document text (will be embedded)
            company_id: Insurance company (CRITICAL for isolation)
            customer_id: Claimant identifier
            doc_type: "policy" | "guideline" | "historical_claim"
            title: Human-readable title
            source: Document origin
            metadata: Additional JSON metadata

        Returns:
            Document UUID in Weaviate
        """
        try:
            collection = self.client.collections.get(collection_name)

            # INTERVIEW POINT: What happens here?
            # Weaviate uses OpenAI to embed the content text into a 1536-dim vector
            # This vector captures semantic meaning:
            # - "Emergency room visit" and "ER visit" → similar vectors
            # - "Heart surgery" and "Appendicitis" → different vectors

            document_id = collection.data.insert(
                properties={
                    "content": content,
                    "company_id": company_id,
                    "customer_id": customer_id,
                    "doc_type": doc_type,
                    "title": title,
                    "source": source,
                    "metadata_": metadata or {},
                    "created_at": datetime.utcnow().isoformat(),
                    "updated_at": datetime.utcnow().isoformat()
                }
            )

            logger.info(f"✓ Indexed document '{title}' (company={company_id})")
            return document_id

        except Exception as e:
            logger.error(f"✗ Error indexing document: {str(e)}")
            raise

    def hybrid_search(
        self,
        collection_name: str,
        query_text: str,
        company_id: str,
        doc_type: str = None,
        limit: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Perform HYBRID SEARCH in Weaviate.

        INTERVIEW EXPLANATION - CRITICAL CONCEPT:

        Hybrid Search = Keyword Search + Vector Search Combined

        Why two searches?
        1. KEYWORD SEARCH: Fast, matches exact terms
           - Query: "emergency room"
           - Finds: "emergency room visit", "ER", "emergency"

        2. VECTOR SEARCH: Semantic, finds similar meaning
           - Query: "heart emergency"
           - Finds: "cardiac event", "MI", "chest pain" (semantically similar)

        COMBINING BOTH:
        - Keyword catches exact matches (high precision)
        - Vector catches semantic similarities (high recall)
        - Result: Best of both worlds

        MULTI-TENANT FILTERING:
        - WHERE company_id = 'hdfc-life'
        - ENSURES Company A never sees Company B's documents
        - This is CRITICAL for security

        Args:
            collection_name: Collection to search
            query_text: Search query (will be embedded)
            company_id: Filter to this company only (CRITICAL)
            doc_type: Optional filter by document type
            limit: Number of results to return

        Returns:
            List of documents with similarity scores
        """
        try:
            collection = self.client.collections.get(collection_name)

            # Build WHERE filter for multi-tenant isolation
            # INTERVIEW POINT: This is how we prevent data leakage
            where_filter = {
                "path": ["company_id"],
                "operator": "Equal",
                "valueString": company_id
            }

            # Optionally add doc_type filter
            if doc_type:
                where_filter = {
                    "operands": [
                        where_filter,
                        {
                            "path": ["doc_type"],
                            "operator": "Equal",
                            "valueString": doc_type
                        }
                    ],
                    "operator": "And"
                }

            # Execute hybrid search
            # INTERVIEW POINT: Weaviate combines:
            # 1. BM25 keyword search
            # 2. Vector similarity search
            # 3. Fuses results (default: average ranking)

            results = collection.query.hybrid(
                query=query_text,
                where=where_filter,
                limit=limit,
                return_metadata=MetadataQuery(score=True)  # Get similarity score
            )

            # Format results for return
            documents = []
            for obj in results.objects:
                documents.append({
                    "id": obj.uuid,
                    "title": obj.properties.get("title", ""),
                    "content": obj.properties.get("content", ""),
                    "doc_type": obj.properties.get("doc_type", ""),
                    "source": obj.properties.get("source", ""),
                    "similarity_score": obj.metadata.score,  # 0-1 relevance score
                    "metadata": obj.properties.get("metadata_", {})
                })

            logger.info(f"✓ Hybrid search found {len(documents)} documents")
            return documents

        except Exception as e:
            logger.error(f"✗ Hybrid search error: {str(e)}")
            return []

    def vector_search(
        self,
        collection_name: str,
        query_text: str,
        company_id: str,
        limit: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Pure VECTOR SEARCH (semantic similarity only).

        INTERVIEW EXPLANATION:
        Unlike hybrid search, this uses ONLY vector similarity.
        - Faster but less precise
        - Good for: "Find similar past claims"
        - Bad for: "Find specific policy clause"

        Use case: Finding similar historical claims to compare with current claim
        """
        try:
            collection = self.client.collections.get(collection_name)

            results = collection.query.near_text(
                query=query_text,
                where={
                    "path": ["company_id"],
                    "operator": "Equal",
                    "valueString": company_id
                },
                limit=limit,
                return_metadata=MetadataQuery(score=True)
            )

            documents = []
            for obj in results.objects:
                documents.append({
                    "id": obj.uuid,
                    "title": obj.properties.get("title", ""),
                    "content": obj.properties.get("content", ""),
                    "similarity_score": obj.metadata.score
                })

            return documents

        except Exception as e:
            logger.error(f"✗ Vector search error: {str(e)}")
            return []

    def close(self):
        """Close Weaviate connection."""
        if self.client:
            self.client.close()
            logger.info("✓ Closed Weaviate connection")
